id = "lima"
name = "Lima"
description = "Lima language support powered by the Lima Language Server."
version = "0.1.0"
schema_version = 1
authors = ["Michael Kortstiege"]
repository = "https://github.com/limaformat/lima"

[language_servers.lima-language-server]
name = "Lima Language Server"
language = "Lima"
language_ids = { Lima = "lima" }

[grammars.yaml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-yaml"
commit = "a1c4812a73ec5e089de8e441fdea3a921e8d5079"
