import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  CORPUS_GRAMMAR_CASES,
  type CorpusGrammarCase,
  type CorpusQuoteRange,
} from "../corpus-grammar-cases.js";

const ROOT = resolve(__dirname, "../../..");
const SUBLIME_OUTPUT = resolve(
  ROOT,
  "editors/lsp/test/syntax_test_lima_corpus.lima",
);
const EMACS_OUTPUT = resolve(
  ROOT,
  "editors/lsp/test/lima-mode-test-corpus.el",
);

writeGenerated(SUBLIME_OUTPUT, generateSublime());
writeGenerated(EMACS_OUTPUT, generateEmacs());
console.log(
  `generated ${CORPUS_GRAMMAR_CASES.length} corpus cases for Sublime and Emacs`,
);

function writeGenerated(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
}

function generateSublime(): string {
  const lines = [
    '# SYNTAX TEST "Packages/User/Lima.sublime-syntax"',
    "# Generated by editors/shared/scripts/generate-corpus-syntax-tests.ts.",
    "# Do not edit by hand.",
    "",
  ];
  for (const fixture of CORPUS_GRAMMAR_CASES) {
    lines.push(`# Corpus fixture: ${fixture.id}`);
    lines.push(fixture.input);
    addSublimeCommentAssertions(lines, fixture);
    for (const quote of fixture.quoteRanges) {
      addSublimeQuoteAssertions(lines, fixture.input, quote);
    }
    for (const quote of fixture.quoteRanges.filter(({ closed }) => !closed)) {
      // Sublime syntax tests share tokenizer state across their source lines.
      // Close an intentionally unterminated fixture (and any surrounding flow
      // collection) so it cannot affect the next independent corpus case.
      lines.push(`${quote.quote === "double" ? '"' : "'"}]}`);
    }
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

function addSublimeCommentAssertions(
  lines: string[],
  fixture: CorpusGrammarCase,
): void {
  if (fixture.commentStart !== null) {
    lines.push(
      sublimeAssertion(
        fixture.commentStart,
        fixture.input.length - fixture.commentStart,
        "comment.line.number-sign.lima",
      ),
    );
    if (fixture.commentStart > 0) {
      lines.push(
        sublimeAssertion(
          fixture.commentStart - 1,
          1,
          "source.lima - comment.line.number-sign.lima",
        ),
      );
    }
    return;
  }
  for (const index of hashOffsets(fixture.input)) {
    lines.push(
      sublimeAssertion(
        index,
        1,
        "source.lima - comment.line.number-sign.lima",
      ),
    );
  }
}

function addSublimeQuoteAssertions(
  lines: string[],
  input: string,
  quote: CorpusQuoteRange,
): void {
  const [start, end] = quote.range;
  const scope =
    quote.kind === "key"
      ? "entity.name.tag.lima"
      : `string.quoted.${quote.quote}.lima`;
  if (start === 0) {
    // Native syntax-test caret annotations cannot occupy columns 0 or 1,
    // because those columns contain `# `. Use the start-of-line arrow for
    // column 0 and cover the remainder from column 2 onward.
    lines.push(`# <- ${scope}`);
    if (end > 2) lines.push(sublimeAssertion(2, end - 2, scope));
  } else {
    lines.push(sublimeAssertion(start, end - start, scope));
  }
  if (end < input.length) {
    lines.push(sublimeAssertion(end, 1, `source.lima - ${scope}`));
  }
}

function sublimeAssertion(start: number, length: number, scope: string): string {
  if (start < 2) {
    throw new Error(`Sublime caret assertions cannot start at column ${start}`);
  }
  return `#${" ".repeat(start - 1)}${"^".repeat(Math.max(1, length))} ${scope}`;
}

function generateEmacs(): string {
  const lines = [
    ";;; lima-mode-test-corpus.el --- Generated corpus tests -*- lexical-binding: t; -*-",
    ";; Generated by editors/shared/scripts/generate-corpus-syntax-tests.ts.",
    ";; Do not edit by hand.",
    "",
    "(require 'ert)",
    "(unless (fboundp 'lima-test--face-at)",
    '  (error "Load lima-mode-test.el before this generated test file"))',
    "",
  ];
  for (const fixture of CORPUS_GRAMMAR_CASES) {
    const name = fixture.id.replace(/[^a-zA-Z0-9-]+/g, "-");
    lines.push(`(ert-deftest lima-mode-corpus-${name} ()`);
    const assertions = emacsAssertions(fixture);
    if (assertions.length === 0) {
      lines.push("  (should t))");
    } else {
      lines.push(...assertions.map((assertion) => `  ${assertion}`));
      lines[lines.length - 1] += ")";
    }
    lines.push("");
  }
  lines.push(";;; lima-mode-test-corpus.el ends here", "");
  return lines.join("\n");
}

function emacsAssertions(fixture: CorpusGrammarCase): string[] {
  const input = elispString(fixture.input);
  const faceAt = (offset: number) =>
    `(lima-test--face-at ${input} ${input} ${offset})`;
  const assertions: string[] = [];
  if (fixture.commentStart !== null) {
    assertions.push(
      `(should (eq ${faceAt(fixture.commentStart)} 'font-lock-comment-face))`,
    );
    if (fixture.commentStart > 0) {
      assertions.push(
        `(should-not (eq ${faceAt(fixture.commentStart - 1)} 'font-lock-comment-face))`,
      );
    }
  } else {
    for (const index of hashOffsets(fixture.input)) {
      assertions.push(
        `(should-not (eq ${faceAt(index)} 'font-lock-comment-face))`,
      );
    }
  }
  for (const quote of fixture.quoteRanges) {
    const [start, end] = quote.range;
    // Emacs exposes one winning face rather than TextMate's scope stack.
    // Test the opening delimiter, which is never replaced by an escape face.
    const face = "font-lock-string-face";
    assertions.push(`(should (eq ${faceAt(start)} '${face}))`);
    if (end < fixture.input.length) {
      assertions.push(`(should-not (eq ${faceAt(end)} '${face}))`);
    }
  }
  return assertions;
}

function elispString(value: string): string {
  return JSON.stringify(value).replaceAll("\\u", "\\\\u");
}

function hashOffsets(input: string): number[] {
  const offsets: number[] = [];
  for (
    let index = input.indexOf("#");
    index >= 0;
    index = input.indexOf("#", index + 1)
  ) {
    offsets.push(index);
  }
  return offsets;
}
