;;; lima-mode-test-corpus.el --- Generated corpus tests -*- lexical-binding: t; -*-
;; Generated by editors/shared/scripts/generate-corpus-syntax-tests.ts.
;; Do not edit by hand.

(require 'ert)
(unless (fboundp 'lima-test--face-at)
  (error "Load lima-mode-test.el before this generated test file"))

(ert-deftest lima-mode-corpus-core-document-inline-pipeline-comment-stripped ()
  (should (eq (lima-test--face-at "title: Hello World # comment" "title: Hello World # comment" 19) 'font-lock-comment-face))
  (should-not (eq (lima-test--face-at "title: Hello World # comment" "title: Hello World # comment" 18) 'font-lock-comment-face)))

(ert-deftest lima-mode-corpus-core-document-inline-pipeline-hash-in-quotes-literal ()
  (should-not (eq (lima-test--face-at "link: \"https://example.com/page#section\"" "link: \"https://example.com/page#section\"" 31) 'font-lock-comment-face))
  (should (eq (lima-test--face-at "link: \"https://example.com/page#section\"" "link: \"https://example.com/page#section\"" 6) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-document-inline-pipeline-quoted-plus-trailing-comment ()
  (should (eq (lima-test--face-at "title: \"Hello\" # comment" "title: \"Hello\" # comment" 15) 'font-lock-comment-face))
  (should-not (eq (lima-test--face-at "title: \"Hello\" # comment" "title: \"Hello\" # comment" 14) 'font-lock-comment-face))
  (should (eq (lima-test--face-at "title: \"Hello\" # comment" "title: \"Hello\" # comment" 7) 'font-lock-string-face))
  (should-not (eq (lima-test--face-at "title: \"Hello\" # comment" "title: \"Hello\" # comment" 14) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-document-inline-pipeline-trailing-content-non-strict ()
  (should (eq (lima-test--face-at "title: \"Hello\" trailing" "title: \"Hello\" trailing" 7) 'font-lock-string-face))
  (should-not (eq (lima-test--face-at "title: \"Hello\" trailing" "title: \"Hello\" trailing" 14) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-document-inline-pipeline-trailing-content-strict ()
  (should (eq (lima-test--face-at "title: \"Hello\" trailing" "title: \"Hello\" trailing" 7) 'font-lock-string-face))
  (should-not (eq (lima-test--face-at "title: \"Hello\" trailing" "title: \"Hello\" trailing" 14) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-keys-quoted-double-quoted-decodes-escapes ()
  (should (eq (lima-test--face-at "\"say \\\"hi\\\"\": value" "\"say \\\"hi\\\"\": value" 0) 'font-lock-string-face))
  (should-not (eq (lima-test--face-at "\"say \\\"hi\\\"\": value" "\"say \\\"hi\\\"\": value" 12) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-keys-quoted-escape-newline-double-quoted-is-a-key ()
  (should (eq (lima-test--face-at "\"a\\nb\": value" "\"a\\nb\": value" 0) 'font-lock-string-face))
  (should-not (eq (lima-test--face-at "\"a\\nb\": value" "\"a\\nb\": value" 6) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-keys-quoted-space-before-colon-non-strict ()
  (should (eq (lima-test--face-at "\"first name\" : Alice" "\"first name\" : Alice" 0) 'font-lock-string-face))
  (should-not (eq (lima-test--face-at "\"first name\" : Alice" "\"first name\" : Alice" 12) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-keys-quoted-space-before-colon-strict ()
  (should (eq (lima-test--face-at "\"first name\" : Alice" "\"first name\" : Alice" 0) 'font-lock-string-face))
  (should-not (eq (lima-test--face-at "\"first name\" : Alice" "\"first name\" : Alice" 12) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-double-quote-unterminated-escaped-quote-non-strict ()
  (should (eq (lima-test--face-at "v: \"abc\\\"" "v: \"abc\\\"" 3) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-double-quote-unterminated-escaped-quote-strict ()
  (should (eq (lima-test--face-at "v: \"abc\\\"" "v: \"abc\\\"" 3) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-double-quote-unterminated-non-strict ()
  (should (eq (lima-test--face-at "v: \"hello world" "v: \"hello world" 3) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-double-quote-unterminated-strict ()
  (should (eq (lima-test--face-at "v: \"hello world" "v: \"hello world" 3) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-flow-mapping-value-trailing-content-strict ()
  (should (eq (lima-test--face-at "m: {k: \"a\" x}" "m: {k: \"a\" x}" 7) 'font-lock-string-face))
  (should-not (eq (lima-test--face-at "m: {k: \"a\" x}" "m: {k: \"a\" x}" 10) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-flow-sequence-trailing-content-strict ()
  (should (eq (lima-test--face-at "v: [\"x\" trailing]" "v: [\"x\" trailing]" 4) 'font-lock-string-face))
  (should-not (eq (lima-test--face-at "v: [\"x\" trailing]" "v: [\"x\" trailing]" 7) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-flow-sequence-unterminated-quote-strict ()
  (should (eq (lima-test--face-at "v: [\"abc]" "v: [\"abc]" 4) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-single-quote-trailing-even-backslash-run ()
  (should (eq (lima-test--face-at "v: 'C:\\\\dir\\\\'" "v: 'C:\\\\dir\\\\'" 3) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-single-quote-unterminated-escaped-quote-non-strict ()
  (should (eq (lima-test--face-at "v: 'abc\\'" "v: 'abc\\'" 3) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-single-quote-unterminated-escaped-quote-strict ()
  (should (eq (lima-test--face-at "v: 'abc\\'" "v: 'abc\\'" 3) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-single-quote-unterminated-non-strict ()
  (should (eq (lima-test--face-at "v: 'hello world" "v: 'hello world" 3) 'font-lock-string-face)))

(ert-deftest lima-mode-corpus-core-strings-single-quote-unterminated-strict ()
  (should (eq (lima-test--face-at "v: 'hello world" "v: 'hello world" 3) 'font-lock-string-face)))

;;; lima-mode-test-corpus.el ends here
